name: Test

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  # https://github.com/pre-commit/action
  pre-commit:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v2.0.3

  test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python:
          - "3.7"
          - "3.10"
      fail-fast: false

    defaults:
      run:
        # Needed to activate conda environment
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3

      # https://github.com/conda-incubator/setup-miniconda
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "${{ matrix.python }}"
          mamba-version: "*"
          channels: conda-forge

      - name: Install dependencies
        run: |
          conda install -y conda mamba
          pip install -r requirements-test.txt

      - name: Install package
        run: |
          pip install .

      - name: Run tests
        run: |
          pytest -vs test/test_downloader.py

      - name: Run tests
        run: |
          pytest -vs test/
